version: 2

models:
  - name: stg_greenery_addresses
    description: staging table for greenery addresses
    columns:
      - name: address_id
      - name: address
      - name: zipcode
      - name: state
      - name: country    

  - name: stg_greenery_users
    description: staging table for greenery users
    columns:
      - name: user_id
      - name: first_name
      - name: last_name
      - name: email
      - name: phone_number
      - name: created_at
      - name: updated_at
      - name: address_id

  - name: stg_greenery_promos
    description: staging table for greenery promos
    columns:
      - name: promo_id
      - name: discount
      - name: status

  - name: stg_greenery_products
    description: staging table for greenery products
    columns:
      - name: product_id
      - name: name
      - name: price
      - name: inventory

  - name: stg_greenery_orders
    description: staging table for greenery orders  
    columns:
      - name: order_id
      - name: user_id
      - name: promo_id
      - name: address_id
      - name: created_at
      - name: order_cost
      - name: shipping_cost
      - name: order_total
      - name: tracking_id
      - name: shipping_service
      - name: estimated_delivery_at
      - name: delivered_at
      - name: status

  - name: stg_greenery_order_items
    description: staging table for greenery order_items
    columns:
      - name: order_id
      - name: product_id
      - name: quantity
      
  - name: stg_greenery_events
    description: staging table for greenery events
    columns:
      - name: event_id
      - name: session_id
      - name: user_id
      - name: page_url
      - name: created_at
      - name: event_type
      - name: order_id
      - name: product_id